# Generated by Django 3.2.25 on 2024-06-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پیام')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='متن پیام کاربر')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده / نشده')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('response_message', models.TextField(verbose_name='پیام ادمین')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
