# Generated by Django 3.2.25 on 2024-06-14 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم دسته بندی')),
                ('url_title', models.CharField(max_length=100, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.CharField(default=True, max_length=100, verbose_name='فعال / غیرفعال')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.articlecategory', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': ' دسته بندی مقالات',
                'verbose_name_plural': 'دسته بندی های مقالات',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='عنوان در url')),
                ('short_description', models.CharField(max_length=400, verbose_name='توضیحات کوتاه')),
                ('text', models.TextField(verbose_name='توضیحات کامل')),
                ('image', models.ImageField(upload_to='images/article', verbose_name='عکس مقاله')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('auther', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('selected_category', models.ManyToManyField(to='article.ArticleCategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
