# Generated by Django 3.2.25 on 2024-06-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articlecategory_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='url_title',
        ),
    ]
