# Generated by Django 5.0.6 on 2024-06-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='نمایش داده شود/ نشود'),
        ),
    ]
