# Generated by Django 5.0.6 on 2024-06-30 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0001_initial'),
        ('products', '0026_remove_products_brand_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='products_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_color', verbose_name='رنگ محصول'),
        ),
    ]
