# Generated by Django 5.0.6 on 2024-07-01 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0003_rename_products_color_orderdetail_products_color_id'),
        ('products', '0026_remove_products_brand_products_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='products_color_id',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='products_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_color', verbose_name='رنگ محصول'),
        ),
    ]
