# Generated by Django 5.0.6 on 2024-07-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0004_remove_orderdetail_products_color_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='side',
            field=models.CharField(blank=True, choices=[('left', 'چپ'), ('right', 'راست'), ('both', 'هر دو')], max_length=10, null=True),
        ),
    ]
