# Generated by Django 5.0.6 on 2024-07-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0005_orderdetail_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='side',
            field=models.CharField(blank=True, choices=[('left', 'چپ'), ('right', 'راست')], max_length=10, null=True),
        ),
    ]
