# Generated by Django 5.0.6 on 2024-07-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0007_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کاربر فعلی'),
        ),
    ]
