# Generated by Django 5.0.6 on 2024-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0008_order_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ پرداخت شده نهایی کاربر'),
        ),
    ]
