# Generated by Django 5.0.6 on 2024-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0009_order_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.IntegerField(blank=True, max_length=50, null=True, verbose_name='کد پستی')),
                ('phone_number', models.IntegerField(max_length=50, verbose_name='شماره موبایل')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='ایمیل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت خرید')),
            ],
            options={
                'verbose_name': 'مشخصات خرید کننده',
                'verbose_name_plural': 'مشخصات خرید کنندگان',
            },
        ),
    ]
