# Generated by Django 5.0.6 on 2024-07-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0010_final_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_payment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='final_payment',
            name='email',
        ),
        migrations.AlterField(
            model_name='final_payment',
            name='phone_number',
            field=models.IntegerField(verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='final_payment',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد پستی'),
        ),
    ]
