# Generated by Django 5.0.6 on 2024-07-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0011_remove_final_payment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_payment',
            name='send_method',
            field=models.CharField(choices=[('post', 'پست'), ('terminal', 'ترمینال'), ('barbary', 'باربری'), ('t_pax', 'تیپاکس')], default='post', max_length=20),
        ),
    ]
