# Generated by Django 5.0.6 on 2024-07-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0012_final_payment_send_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_payment',
            name='send_method',
            field=models.CharField(choices=[('post', 'پست'), ('terminal', 'ترمینال'), ('barbary', 'باربری'), ('t_pax', 'تیپاکس')], default='post', max_length=20, verbose_name='روش ارسال'),
        ),
    ]
