# Generated by Django 5.0.6 on 2024-07-27 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0013_alter_final_payment_send_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_list.order', verbose_name='شماره فاکتور'),
        ),
    ]
