# Generated by Django 5.0.6 on 2024-07-27 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_list', '0014_final_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_payment',
            name='order',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_list.order', verbose_name='شماره فاکتور'),
        ),
    ]
