# Generated by Django 3.2.25 on 2024-06-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_acitive_code',
            field=models.CharField(editable=False, max_length=300, verbose_name='کد تااید ایمل'),
        ),
    ]
