# Generated by Django 3.2.25 on 2024-06-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_email_acitive_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_acitive_code',
            new_name='email_active_code',
        ),
    ]
