# Generated by Django 3.2.25 on 2024-06-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_us',
            field=models.TextField(verbose_name='متن درباره ما'),
        ),
    ]
