# Generated by Django 3.2.25 on 2024-06-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_alter_sitesettings_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(upload_to='uploads/site_logo', verbose_name='لوگو'),
        ),
    ]
