# Generated by Django 5.0.6 on 2024-06-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_alter_sitesettings_site_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(verbose_name='آدرس url')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='sliders/image', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
