# Generated by Django 5.0.6 on 2024-06-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0004_sliders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sliders',
        ),
    ]
