# Generated by Django 5.0.6 on 2024-06-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0006_link_boxes_sitefooter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='نام بنر')),
                ('url_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس بنر')),
                ('position', models.CharField(choices=[('home', 'خانه'), ('products', 'محصولات'), ('articles', 'مقالات')], max_length=200, verbose_name='در کدام صفحه نمایش داده شود')),
                ('image', models.ImageField(upload_to='baners/images', verbose_name='تصویر بنر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
