# Generated by Django 5.0.6 on 2024-07-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0007_sitebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='q_and_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ به سوال')),
            ],
            options={
                'verbose_name': 'پرسش و پاسخ',
                'verbose_name_plural': 'پرس ها و پاسخ های متداول',
            },
        ),
    ]
