# Generated by Django 3.2.25 on 2024-06-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم محصول')),
                ('short_description', models.TextField(db_index=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default='', verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/uploads', verbose_name='تصویر محصول')),
                ('is_delete', models.BooleanField(default=False, verbose_name='موجود/حذف شده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
