# Generated by Django 3.2.25 on 2024-06-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_brand',
            name='brand_url',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='عنوان در url'),
        ),
    ]
