# Generated by Django 3.2.25 on 2024-06-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productcars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcars',
            options={'verbose_name': 'خودرو ', 'verbose_name_plural': ' خودرو ها'},
        ),
    ]
