# Generated by Django 3.2.25 on 2024-06-12 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_productcars_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcars',
            name='car_products',
        ),
        migrations.RemoveField(
            model_name='products',
            name='selected_category',
        ),
        migrations.AddField(
            model_name='products',
            name='car_products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productcars', verbose_name='خودرو'),
        ),
    ]
