# Generated by Django 3.2.25 on 2024-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20240612_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcars',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیر فعال'),
        ),
    ]
