# Generated by Django 5.0.6 on 2024-06-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productcars_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcars',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/image', verbose_name='تصویر خودرو'),
        ),
    ]
