# Generated by Django 5.0.6 on 2024-06-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productcars_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcars',
            name='short_description',
            field=models.TextField(default='برای نمایش محصولات روی دکمه زیر کلیک کنید', verbose_name='توضیحات کوتاه'),
        ),
    ]
