# Generated by Django 5.0.6 on 2024-06-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/categories/category', verbose_name='عکس دسته بندی'),
        ),
    ]
