# Generated by Django 5.0.6 on 2024-06-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/categories/brands', verbose_name='تصویر برند'),
        ),
    ]
