# Generated by Django 5.0.6 on 2024-06-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_brand_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام رنگ')),
                ('url_title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان در url')),
                ('hex_value', models.CharField(max_length=20, verbose_name='کد رنگ')),
            ],
            options={
                'verbose_name': 'رنگ محصولات',
                'verbose_name_plural': 'رنگ های محصولات',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(db_index=True, to='products.product_color', verbose_name='رنگ های محصول'),
        ),
    ]
