# Generated by Django 5.0.6 on 2024-06-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_color_products_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand',
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.ManyToManyField(db_index=True, to='products.product_brand', verbose_name='برند ها'),
        ),
    ]
