# Generated by Django 5.0.6 on 2024-07-01 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_products_brand_products_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceByProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_by_color', models.ImageField(upload_to='', verbose_name='قیمت محصول بر اساس رنگ')),
                ('colors', models.ManyToManyField(to='products.product_color', verbose_name='رنگ ها')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قیمت محصول بر اساس رنگ',
                'verbose_name_plural': 'قیمت محصولات بر اساس رنگ ها ',
            },
        ),
    ]
