# Generated by Django 5.0.6 on 2024-07-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_pricebyproductcolor_price_by_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='position',
            field=models.CharField(choices=[('جلو', 'Front')], max_length=200, null=True, verbose_name='محل نصب'),
        ),
    ]
