# Generated by Django 5.0.6 on 2024-07-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_products_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.CharField(choices=[('plastic', 'پلی اتیلن'), ('felez', 'فلز')], max_length=200, null=True, verbose_name='جنس'),
        ),
        migrations.AlterField(
            model_name='products',
            name='position',
            field=models.CharField(choices=[('front', 'جلو'), ('right_front', 'جلو راست'), ('left_front', 'جلو چپ'), ('right', ' راست'), ('left', 'چپ'), ('back', 'عقب'), ('right_back', 'عقب راست'), ('left_back', 'عقب چپ')], max_length=200, null=True, verbose_name='محل نصب'),
        ),
    ]
