# Generated by Django 5.0.6 on 2024-07-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_products_material_alter_products_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cars',
            field=models.CharField(choices=[('p405', ' پژو RD , پژو405'), ('pars', 'پژو پارس')], max_length=500, null=True, verbose_name='مناسب برای خودرو'),
        ),
    ]
