# Generated by Django 5.0.6 on 2024-07-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_products_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='garanti',
            field=models.CharField(choices=[('zemanat_none', 'فاقد ضمانت از سمت تولید کننده میباشد'), ('zemanat_1_sale', 'دارای 1 سال ضمانت رنگ میباشد'), ('zemanat_5_sale', 'دارای 5 سال ضمانت رنگ میباشد')], max_length=200, null=True, verbose_name='وضعیت ضمانت'),
        ),
        migrations.AlterField(
            model_name='products',
            name='cars',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='مناسب برای خودرو'),
        ),
    ]
