# Generated by Django 5.0.6 on 2024-07-03 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_products_garanti_alter_products_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcars',
            name='car_image',
        ),
    ]
