# Generated by Django 5.0.6 on 2024-07-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sugest',
            field=models.IntegerField(blank=True, null=True, verbose_name='محصولات پیشنهادی'),
        ),
    ]
