# Generated by Django 5.0.6 on 2024-07-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_products_sugest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sugest',
        ),
        migrations.AddField(
            model_name='product_category',
            name='sugest',
            field=models.ManyToManyField(blank=True, null=True, to='products.product_category', verbose_name='محصولات پیشنهادی'),
        ),
    ]
