# Generated by Django 5.0.6 on 2024-07-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_products_main_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='main_position',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا قطعه دارای جهت بندی میباشد'),
        ),
    ]
