# Generated by Django 5.0.6 on 2024-07-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_alter_products_main_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='main_position',
            new_name='side',
        ),
    ]
