# Generated by Django 5.0.6 on 2024-07-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_rename_main_position_products_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='side',
            field=models.BooleanField(default=False, verbose_name='آیا قطعه دارای جهت بندی میباشد'),
        ),
    ]
