# Generated by Django 5.0.6 on 2024-07-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_products_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='محل نصب')),
            ],
            options={
                'verbose_name': 'محل نصب قطعه',
                'verbose_name_plural': 'محب نصب قطعات',
            },
        ),
        migrations.RemoveField(
            model_name='product_category',
            name='sugest',
        ),
        migrations.AlterField(
            model_name='products',
            name='colors',
            field=models.ManyToManyField(blank=True, db_index=True, to='products.product_color', verbose_name='رنگ های محصول'),
        ),
        migrations.AddField(
            model_name='products',
            name='suggest',
            field=models.ManyToManyField(blank=True, db_index=True, to='products.suggestion', verbose_name='ایجاد ارتباط برای پیشنهاد'),
        ),
    ]
