# Generated by Django 5.0.6 on 2024-07-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_suggestion_remove_product_category_sugest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='has_color',
            field=models.BooleanField(db_index=True, default=False, verbose_name='محصول دارای رنگ بندی است ؟'),
        ),
    ]
