# Generated by Django 5.0.6 on 2024-07-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_products_has_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='url_title',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='اسم دسته بندی در url'),
        ),
    ]
